apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argo-demo
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 8081
      targetPort: http
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: argo-demo
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path:  "/"
        backend:
          service:
            name: nginx
            port:
              number: 8081
